### ISSUE TITLE
Implement timer at side decking state

### ISSUE THREAD

**Issue by diangogav** [diangogav/EDOpro-server-ts#67]
## Description
Actually, if a player wants to leave the duel during side decking, the duel never ends and the other player will be obliged to close the duel. To prevent this behavior, we need to implement a timer during the side decking state, which will cause a duel loss if the user does not complete the side decking during this time.

## Tasks
- [ ] Implement a timer during the side decking state when a player completes side decking.

## Acceptance Criteria
- [ ] If player 1 completes the side decking, initiate the timer; if player 2 does not complete the side decking, player 1 wins the duel.
- [ ] If both players do not complete the side decking, do nothing.
