### ISSUE TITLE
[MyCard] Implements START param.

### ISSUE THREAD

**Issue by diangogav** [diangogav/EDOpro-server-ts#68]
## Description
Implement the `START` parameter to set the initial card count for each player in a duel.

## Tasks
- [x] Implement the `st` parameter for the `START` command in the `RuleMappings.ts` file.

## Acceptance Criteria
- [x] If the create room command includes `st[number]`, for example, `st6`, the initial hand count for each player should be the specified number, in this example, 6.

- [x] Should not allow times lower than 1 and greater than 40.

## NOTES

Please, for this issue, using the `mycard` branch as the main branch

**Comment by diangogav** [comment]
Solved https://github.com/diangogav/EDOpro-server-ts/pull/84
