### ISSUE TITLE
[MyCard] Implement TIME param.

### ISSUE THREAD

**Issue by diangogav** [diangogav/EDOpro-server-ts#69]
## Description
Implement the `TIME` parameter to set the time for each player's turn.

## Tasks
- [x] Implement the `tm` parameter for the `TIME` command in the `RuleMappings.ts` file.

## Acceptance Criteria
- [x] If the create room command includes `tm[number]`, for example, `tm5`, the time for each player's turn should be the specified number in minutes, in this example, 5 minutes.
- [x] Should not allow times lower than 1 and greater than 999.

## NOTES

Please, for this issue, using the `mycard` branch as the main branch

**Comment by diangogav** [comment]
solved:
https://github.com/diangogav/EDOpro-server-ts/pull/79
https://github.com/diangogav/EDOpro-server-ts/pull/80
