### ISSUE TITLE
[MyCard] Implement DRAW param

### ISSUE THREAD

**Issue by diangogav** [diangogav/EDOpro-server-ts#70]
## Description
Implement the `DRAW` parameter to set the draw count for each player's turn.

## Tasks
- [x] Implement the `dr` parameter for the `DRAW` command in the `RuleMappings.ts` file.

## Acceptance Criteria
- [x] If the create room command includes `dr[number]`, for example, `dr2`, each player's draw turn should be the specified number, in this example, 2 cards.
- [x] Should not allow times lower than 0 and greater than 35.

## NOTES

Please, for this issue, using the `mycard` branch as the main branch
